{
    "name": "AI",
    "category": "Hidden",
    "version": "1.0",
    "depends": ["base", "webx"],
    "data": [
        "data/hashy_config.xml",
        "data/base_cron_data.xml",
        "data/ai_client_actions.xml",
        "security/base.model.access.csv",
        "views/ai_agent_config.xml",
        "views/ai_message.xml",
        "views/ai_session.xml",
        "views/ai_knowledge_views.xml",
        "views/ai_knowledge_wizard_views.xml",
        "views/base_report_views.xml",
        "views/menu.xml",
    ],
    "assets": {
        "webx.assets_backend": [
            "static/libs/marked/marked.min.js",
            "static/libs/dompurify/purify.min.js",
            "static/libs/highlightjs/highlight.min.js",
            "static/libs/highlightjs/atom-one-dark.min.css",
            "static/js/class/hashy-auth-helper.js",
            "static/js/store/hashy-ai-store.js",
            "static/js/class/hashy-api-client.js",
            "static/js/utils/hashy-markdown-utils.js",
            "static/js/utils/hashy-message-utils.js",
            "static/js/utils/hashy-file-utils.js",
            "static/js/utils/hashy-api-utils.js",
            "static/js/utils/hashy-auth-utils.js",
            "static/js/utils/hashy-scroll-utils.js",
            "static/js/utils/hashy-session-utils.js",
            "static/js/composables/use-hashy-messages.js",
            "static/js/composables/use-hashy-files.js",
            "static/js/composables/use-hashy-chat.js",
            "static/js/components/hashy-message-content.js",
            "static/js/components/hashy-message-bubble.js",
            "static/js/components/hashy-file-attachment.js",
            "static/js/components/hashy-file-icon.js",
            "static/js/components/hashy-input-area.js",
            "static/js/components/hashy-thinking-indicator.js",
            "static/js/views/hashy-chat-view.js",
            "static/js/layout/hashy-session-icons.js",
            "static/js/layout/hashy-session-warning.js",
            "static/js/layout/topbar-button-hashy.js",
            "static/js/layout/hashy-session-dropdown.js",
            "static/js/views/ai-chat-interface.js",
            "static/css/components/hashy-markdown.css",
            "static/css/components/hashy-file-attachment.css",
            "static/css/**/*.css",
            "static/vue/**/*.vue",
        ]
    },
}
